### ISSUE TITLE
blueP and dbus error 

### ISSUE THREAD

**Issue by VaibhavGaikwadDev** [Coutj/Bluetooth_project#16]
python3 main.py
Traceback (most recent call last):
  File "/home/linuxmint/Bluetooth_project/main.py", line 6, in <module>
    import blueP
  File "/home/linuxmint/Bluetooth_project/blueP.py", line 3, in <module>
    import dbus
ModuleNotFoundError: No module named 'dbus'

**Comment by mediapinta** [comment]
Hi,

I've got a similar error:

```
$ python3 main.py
Traceback (most recent call last):
  File "/home/ifrit/Transferências/Bluetooth_project-master/main.py", line 6, in <module>
    import blueP
  File "/home/ifrit/Transferências/Bluetooth_project-master/blueP.py", line 2, in <module>
    import bluetooth
ModuleNotFoundError: No module named 'bluetooth'

```
Any idea?

Thank you.

Greetings,
ifrit
